spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msorder
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: '/swagger*'

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
flyway:
  locations: classpath:db/migration
  enabled: true